// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alitsdb.proto

package com_alibaba_tsdb_service_api

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MultifieldPoint struct {
	Timestamp            int64              `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metric               string             `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags                 map[string]string  `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Fields               map[string]float64 `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MultifieldPoint) Reset()         { *m = MultifieldPoint{} }
func (m *MultifieldPoint) String() string { return proto.CompactTextString(m) }
func (*MultifieldPoint) ProtoMessage()    {}
func (*MultifieldPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ca79f1ca873329, []int{0}
}
func (m *MultifieldPoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MultifieldPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MultifieldPoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MultifieldPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultifieldPoint.Merge(m, src)
}
func (m *MultifieldPoint) XXX_Size() int {
	return m.Size()
}
func (m *MultifieldPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MultifieldPoint.DiscardUnknown(m)
}

var xxx_messageInfo_MultifieldPoint proto.InternalMessageInfo

func (m *MultifieldPoint) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MultifieldPoint) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *MultifieldPoint) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MultifieldPoint) GetFields() map[string]float64 {
	if m != nil {
		return m.Fields
	}
	return nil
}

type MputRequest struct {
	Points               []*MultifieldPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MputRequest) Reset()         { *m = MputRequest{} }
func (m *MputRequest) String() string { return proto.CompactTextString(m) }
func (*MputRequest) ProtoMessage()    {}
func (*MputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ca79f1ca873329, []int{1}
}
func (m *MputRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MputRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MputRequest.Merge(m, src)
}
func (m *MputRequest) XXX_Size() int {
	return m.Size()
}
func (m *MputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MputRequest proto.InternalMessageInfo

func (m *MputRequest) GetPoints() []*MultifieldPoint {
	if m != nil {
		return m.Points
	}
	return nil
}

type MputResponse struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MputResponse) Reset()         { *m = MputResponse{} }
func (m *MputResponse) String() string { return proto.CompactTextString(m) }
func (*MputResponse) ProtoMessage()    {}
func (*MputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ca79f1ca873329, []int{2}
}
func (m *MputResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MputResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MputResponse.Merge(m, src)
}
func (m *MputResponse) XXX_Size() int {
	return m.Size()
}
func (m *MputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MputResponse proto.InternalMessageInfo

func (m *MputResponse) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func init() {
	proto.RegisterType((*MultifieldPoint)(nil), "com.alibaba.tsdb.service.api.MultifieldPoint")
	proto.RegisterMapType((map[string]float64)(nil), "com.alibaba.tsdb.service.api.MultifieldPoint.FieldsEntry")
	proto.RegisterMapType((map[string]string)(nil), "com.alibaba.tsdb.service.api.MultifieldPoint.TagsEntry")
	proto.RegisterType((*MputRequest)(nil), "com.alibaba.tsdb.service.api.MputRequest")
	proto.RegisterType((*MputResponse)(nil), "com.alibaba.tsdb.service.api.MputResponse")
}

func init() { proto.RegisterFile("alitsdb.proto", fileDescriptor_d8ca79f1ca873329) }

var fileDescriptor_d8ca79f1ca873329 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xeb, 0x40,
	0x14, 0x85, 0x3b, 0x4d, 0x5f, 0x78, 0xb9, 0x7d, 0x8f, 0x57, 0x86, 0xa7, 0x84, 0x52, 0x42, 0xc8,
	0xaa, 0x0a, 0x66, 0x51, 0x17, 0xb5, 0x2e, 0x85, 0xba, 0x91, 0x42, 0x1d, 0xbb, 0x97, 0x49, 0x3b,
	0x96, 0xc1, 0xa4, 0x19, 0x33, 0x37, 0xc5, 0xfe, 0x13, 0x7f, 0x92, 0x4b, 0xf7, 0x6e, 0xa4, 0xfe,
	0x11, 0xc9, 0x24, 0xd8, 0xe2, 0xc2, 0xda, 0xdd, 0xbd, 0x37, 0x39, 0xdf, 0x39, 0x07, 0x06, 0xfe,
	0xf2, 0x58, 0xa2, 0x9e, 0x45, 0xa1, 0xca, 0x52, 0x4c, 0x69, 0x67, 0x9a, 0x26, 0x21, 0x8f, 0x65,
	0xc4, 0x23, 0x1e, 0x9a, 0xbb, 0x16, 0xd9, 0x52, 0x4e, 0x45, 0xc8, 0x95, 0x0c, 0x5e, 0xeb, 0xf0,
	0x6f, 0x94, 0xc7, 0x28, 0xef, 0xa4, 0x88, 0x67, 0xe3, 0x54, 0x2e, 0x90, 0x76, 0xc0, 0x41, 0x99,
	0x08, 0x8d, 0x3c, 0x51, 0x2e, 0xf1, 0x49, 0xd7, 0x62, 0x9b, 0x03, 0x3d, 0x04, 0x3b, 0x11, 0x98,
	0xc9, 0xa9, 0x5b, 0xf7, 0x49, 0xd7, 0x61, 0xd5, 0x46, 0xaf, 0xa0, 0x81, 0x7c, 0xae, 0x5d, 0xcb,
	0xb7, 0xba, 0xcd, 0x5e, 0x3f, 0xfc, 0xce, 0x36, 0xfc, 0x62, 0x19, 0x4e, 0xf8, 0x5c, 0x0f, 0x17,
	0x98, 0xad, 0x98, 0x81, 0xd0, 0x6b, 0xb0, 0xcd, 0x57, 0xed, 0x36, 0x0c, 0x6e, 0xb0, 0x1f, 0xee,
	0xd2, 0x68, 0x4b, 0x60, 0x05, 0x6a, 0xf7, 0xc1, 0xf9, 0x74, 0xa1, 0x2d, 0xb0, 0xee, 0xc5, 0xca,
	0x94, 0x73, 0x58, 0x31, 0xd2, 0xff, 0xf0, 0x6b, 0xc9, 0xe3, 0x5c, 0x54, 0xad, 0xca, 0xe5, 0xbc,
	0x7e, 0x46, 0xda, 0x03, 0x68, 0x6e, 0xf1, 0x76, 0x49, 0xc9, 0x96, 0x34, 0x98, 0x40, 0x73, 0xa4,
	0x72, 0x64, 0xe2, 0x21, 0x17, 0x1a, 0xe9, 0x10, 0x6c, 0x55, 0xe4, 0xd3, 0x2e, 0x31, 0xad, 0x4e,
	0xf6, 0x6a, 0xc5, 0x2a, 0x71, 0xe0, 0xc3, 0x9f, 0x92, 0xaa, 0x55, 0xba, 0xd0, 0xa2, 0x48, 0x94,
	0x09, 0x34, 0x89, 0x7e, 0xb3, 0x62, 0xec, 0x3d, 0xc2, 0x81, 0x11, 0x97, 0xb9, 0xc7, 0x39, 0xde,
	0x94, 0x58, 0x7a, 0x0b, 0x8d, 0x44, 0xe5, 0x48, 0x8f, 0x76, 0x38, 0x6f, 0x42, 0xb7, 0x8f, 0x7f,
	0xf2, 0x6b, 0x99, 0x24, 0xa8, 0x5d, 0xb4, 0x9e, 0xd7, 0x1e, 0x79, 0x59, 0x7b, 0xe4, 0x6d, 0xed,
	0x91, 0xa7, 0x77, 0xaf, 0x16, 0xd9, 0xe6, 0x19, 0x9e, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9f,
	0x76, 0x66, 0xa1, 0x97, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MultiFieldsPutServiceClient is the client API for MultiFieldsPutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MultiFieldsPutServiceClient interface {
	Mput(ctx context.Context, in *MputRequest, opts ...grpc.CallOption) (*MputResponse, error)
}

type multiFieldsPutServiceClient struct {
	cc *grpc.ClientConn
}

func NewMultiFieldsPutServiceClient(cc *grpc.ClientConn) MultiFieldsPutServiceClient {
	return &multiFieldsPutServiceClient{cc}
}

func (c *multiFieldsPutServiceClient) Mput(ctx context.Context, in *MputRequest, opts ...grpc.CallOption) (*MputResponse, error) {
	out := new(MputResponse)
	err := c.cc.Invoke(ctx, "/com.alibaba.tsdb.service.api.MultiFieldsPutService/mput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiFieldsPutServiceServer is the server API for MultiFieldsPutService service.
type MultiFieldsPutServiceServer interface {
	Mput(context.Context, *MputRequest) (*MputResponse, error)
}

// UnimplementedMultiFieldsPutServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMultiFieldsPutServiceServer struct {
}

func (*UnimplementedMultiFieldsPutServiceServer) Mput(ctx context.Context, req *MputRequest) (*MputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mput not implemented")
}

func RegisterMultiFieldsPutServiceServer(s *grpc.Server, srv MultiFieldsPutServiceServer) {
	s.RegisterService(&_MultiFieldsPutService_serviceDesc, srv)
}

func _MultiFieldsPutService_Mput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiFieldsPutServiceServer).Mput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.alibaba.tsdb.service.api.MultiFieldsPutService/Mput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiFieldsPutServiceServer).Mput(ctx, req.(*MputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MultiFieldsPutService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.alibaba.tsdb.service.api.MultiFieldsPutService",
	HandlerType: (*MultiFieldsPutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "mput",
			Handler:    _MultiFieldsPutService_Mput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alitsdb.proto",
}

func (m *MultifieldPoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MultifieldPoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MultifieldPoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Fields) > 0 {
		for k := range m.Fields {
			v := m.Fields[k]
			baseI := i
			i -= 8
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(v))))
			i--
			dAtA[i] = 0x11
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintAlitsdb(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintAlitsdb(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Tags) > 0 {
		for k := range m.Tags {
			v := m.Tags[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintAlitsdb(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintAlitsdb(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintAlitsdb(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Metric) > 0 {
		i -= len(m.Metric)
		copy(dAtA[i:], m.Metric)
		i = encodeVarintAlitsdb(dAtA, i, uint64(len(m.Metric)))
		i--
		dAtA[i] = 0x12
	}
	if m.Timestamp != 0 {
		i = encodeVarintAlitsdb(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MputRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MputRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MputRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Points) > 0 {
		for iNdEx := len(m.Points) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Points[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAlitsdb(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MputResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MputResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MputResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Ret {
		i--
		if m.Ret {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAlitsdb(dAtA []byte, offset int, v uint64) int {
	offset -= sovAlitsdb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MultifieldPoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovAlitsdb(uint64(m.Timestamp))
	}
	l = len(m.Metric)
	if l > 0 {
		n += 1 + l + sovAlitsdb(uint64(l))
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovAlitsdb(uint64(len(k))) + 1 + len(v) + sovAlitsdb(uint64(len(v)))
			n += mapEntrySize + 1 + sovAlitsdb(uint64(mapEntrySize))
		}
	}
	if len(m.Fields) > 0 {
		for k, v := range m.Fields {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovAlitsdb(uint64(len(k))) + 1 + 8
			n += mapEntrySize + 1 + sovAlitsdb(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MputRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Points) > 0 {
		for _, e := range m.Points {
			l = e.Size()
			n += 1 + l + sovAlitsdb(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MputResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ret {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAlitsdb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAlitsdb(x uint64) (n int) {
	return sovAlitsdb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MultifieldPoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlitsdb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MultifieldPoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MultifieldPoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metric", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlitsdb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metric = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlitsdb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAlitsdb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAlitsdb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthAlitsdb
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthAlitsdb
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAlitsdb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthAlitsdb
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthAlitsdb
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipAlitsdb(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthAlitsdb
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlitsdb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fields == nil {
				m.Fields = make(map[string]float64)
			}
			var mapkey string
			var mapvalue float64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAlitsdb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAlitsdb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthAlitsdb
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthAlitsdb
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapvaluetemp uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					mapvaluetemp = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					mapvalue = math.Float64frombits(mapvaluetemp)
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipAlitsdb(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthAlitsdb
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Fields[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlitsdb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MputRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlitsdb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MputRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MputRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Points", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlitsdb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Points = append(m.Points, &MultifieldPoint{})
			if err := m.Points[len(m.Points)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlitsdb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MputResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlitsdb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MputResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MputResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ret", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ret = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAlitsdb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAlitsdb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAlitsdb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAlitsdb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAlitsdb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAlitsdb
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAlitsdb
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAlitsdb
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAlitsdb        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAlitsdb          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAlitsdb = fmt.Errorf("proto: unexpected end of group")
)
